### ISSUE TITLE
Run on google colab

### ISSUE THREAD

**Issue by wassimseif** [hse-aml/intro-to-dl#13]
Hello,
Did anyone managed to run the notebooks on Google colab smoothly ?

**Comment by ZEMUSHKA** [comment]
Hi! We haven't tested there.
You can describe your problems here and we can try to fix them.

**Comment by wassimseif** [comment]
Hello,
mostly it's about downloading the datasets and linking them.

**Comment by ZEMUSHKA** [comment]
I've also found a bunch of other issues with tqdm and sessions, which are now fixed.
You can try it out, for now only week 6 is fully tested in Colab: https://www.coursera.org/learn/intro-to-deep-learning/discussions/weeks/6/threads/x37gW5gbEeiALRJD1UuANA

**Comment by wassimseif** [comment]
Thanks for the help! Will check them

**Comment by wassimseif** [comment]
I'm getting this error when running week 4, adversarial task on google colab. anything wrong in the colab support or from my code ?

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1306       return self._call_tf_sessionrun(
-> 1307           options, feed_dict, fetch_list, target_list, run_metadata)
   1308 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1408           self._session, options, feed_dict, fetch_list, target_list,
-> 1409           run_metadata)
   1410     else:

InvalidArgumentError: You must feed a value for placeholder tensor 'keras_learning_phase' with dtype bool
	 [[Node: keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by wassimseif** [comment]
I had to set the learning phase of keras's backend, 

```python
import keras.backend as K
K.set_learning_phase(1) 
```

**Comment by ZEMUSHKA** [comment]
You most likely used dropout or batchnorm.

These layers behave differently during training and testing that's why keras has that `learning_phase`.
The problem with your code is that you don't use Keras in Keras-way: compile() the model and use fit() and predict() - this way it chooses the correct learning phase automatically: https://github.com/tensorflow/tensorflow/issues/11336#issuecomment-315898065

In your case you use Keras layers, but optimize with TensorFlow calls. That means that all that under-the-hood Keras choice of learning_phase is gone. There's also a catch, during **validation** learning_phase will still be 1, which means that keras will do dropout and you will have worse results. I believe you need to set it to 0 during validation, but you need to check that.
